# -*- coding: utf-8 -*-
"""SMS Spam Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ocEk_XuqcRCLiF94L9f4ZVwtHD_4169x

# SMS Spam Detection

## Importing necessary libraries
"""

!pip install optuna -q
!pip install imbalanced-learn -q
!pip install catboost -q
!pip install nltk -q

import re
import nltk
import pickle
import joblib
import optuna
import kagglehub
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from optuna.storages import RDBStorage
from optuna.samplers import TPESampler
from imblearn.over_sampling import ADASYN
from imblearn.pipeline import Pipeline as ImbPipeline
from kagglehub import KaggleDatasetAdapter
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier, ExtraTreesClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import balanced_accuracy_score, precision_score, recall_score, \
 f1_score, confusion_matrix, classification_report, matthews_corrcoef, \
 roc_auc_score, roc_curve, ConfusionMatrixDisplay, fbeta_score, precision_recall_curve, \
 make_scorer

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

print("All libraries has been imported!")

"""## Loading the dataset"""

# Set the path to the file you'd like to load
file_path = "spam.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/sms-spam-collection-dataset",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
  pandas_kwargs={'encoding': 'latin-1'}
)

df.head()

"""## EDA"""

print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

df.info()

df.columns

df.isnull().sum()

round(df.isnull().sum() / df.shape[0] * 100, 2)

plt.figure(figsize=(10, 5))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.show()

print(f"Number of unique values in 'v1' column: {df['v1'].nunique()}")
print(f"Number of unique values in 'v2' column: {df['v2'].nunique()}")

print(f"Number of duplicated values is {df.duplicated().sum()}")

plt.figure(figsize=(6, 5))
sns.countplot(data=df, x='v1', hue='v1', palette='pastel')
plt.title('Distribution of Spam vs. Ham Messages')
plt.xlabel('Message Type')
plt.ylabel('Count')
plt.grid(axis='y', alpha=0.2)
plt.show()

fig = go.Figure(data=[
    go.Pie(
        labels=df['v1'].value_counts().index,
        values=df['v1'].value_counts().values,
        hole=0.4,
        textinfo='label+percent',
        marker=dict(colors=['#00BFA6', '#6A5ACD'])
    )
])
fig.update_layout(title_text='Distribution of Spam vs. Ham Messages')
fig.show()

"""## Data Preprocessing"""

df.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)

df.drop_duplicates(inplace=True)

encoder = LabelEncoder()
df['v1'] = encoder.fit_transform(df['v1'])

df.head()

X = df.drop('v1', axis=1)
y = df['v1']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

X_train = X_train.squeeze()
X_test = X_test.squeeze()

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

class TextCleaner(BaseEstimator, TransformerMixin):
    """
    A custom transformer for basic text cleaning:
    - Lowercasing
    - Removing punctuation
    - Removing numbers
    - Removing extra whitespaces
    - Removing URLs and emails
    - Removing special characters (e.g., @, #)
    """

    def __init__(self, remove_numbers=True, remove_urls=True):
        self.remove_numbers = remove_numbers
        self.remove_urls = remove_urls

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X.apply(self._clean_text)

    def _clean_text(self, text):
        # Ensure the input is treated as a string
        text = str(text)

        # 1. Lowercase
        text = text.lower()

        # 2. Remove URLs and emails
        if self.remove_urls:
            text = re.sub(r"http\S+|www\S+|https\S+", '', text, flags=re.MULTILINE)
            text = re.sub(r'\S+@\S+', '', text)

        # 3. Remove punctuation and special characters
        text = re.sub(r"[^\w\s]", " ", text)

        # 4. Remove numbers
        if self.remove_numbers:
            text = re.sub(r'\d+', '', text)

        # 5. Remove multiple whitespaces
        text = re.sub(r'\s+', ' ', text).strip()

        return text

input_text = "FREE!!! Get your prize now 😎. Visit: https://free-prize.com #Winner123"

output_text = TextCleaner()._clean_text(input_text)

print(output_text)

nltk.download('stopwords', quiet=True)

class StopwordsRemover(BaseEstimator, TransformerMixin):
    """
    Custom transformer to remove stopwords from text.
    Input: Series of strings
    Output: Series of strings with stopwords removed
    """

    def __init__(self, lang='english'):
      self.lang = lang
      self.stopwords = set(stopwords.words(lang))

    def fit(self, X, y=None):
      return self

    def transform(self, X):
      return X.apply(self._remove_stopwords)

    def _remove_stopwords(self, text):
      words = text.split()
      filtered = [word for word in words if word not in self.stopwords]
      return ' '.join(filtered)

text = "This is an example of how we remove the most common words from a sentence"
StopwordsRemover()._remove_stopwords(text)

nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

class Stemmer(BaseEstimator, TransformerMixin):
  """
  Custom transformer to perform stemming on text.
  Input: Series of strings
  Output: Series of strings with stemmed words
  """
  def __init__(self):
    self.stemmer = PorterStemmer()

  def fit(self, X, y=None):
    return self

  def transform(self, X):
    return X.apply(self._stem_text)

  def _stem_text(self, text):
    words = word_tokenize(text)
    stemmed = [self.stemmer.stem(word) for word in words]
    return ' '.join(stemmed)

text = "running runners easily played better"
print(Stemmer()._stem_text(text))

class TextPreprocessor(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.cleaner = TextCleaner()
        self.stop = StopwordsRemover()
        self.stem = Stemmer()
        self.vectorizer = TfidfVectorizer(
            max_features=3000,
            ngram_range=(1, 2),
            sublinear_tf=True,
            norm='l2'
        )

    def fit(self, X, y=None):
        # Fit each component individually
        X_cleaned = self.cleaner.fit_transform(X)
        X_stopwords_removed = self.stop.fit_transform(X_cleaned)
        X_stemmed = self.stem.fit_transform(X_stopwords_removed)
        self.vectorizer.fit(X_stemmed)
        return self

    def transform(self, X):
        # Transform each component individually
        X_cleaned = self.cleaner.transform(X)
        X_stopwords_removed = self.stop.transform(X_cleaned)
        X_stemmed = self.stem.transform(X_stopwords_removed)
        return self.vectorizer.transform(X_stemmed)

pipeline = ImbPipeline(steps=[
    ('preprocessor', TextPreprocessor()),
    ('adasyn', ADASYN(random_state=42)),
    ('model', XGBClassifier(random_state=42))
])

pipeline.fit(X_train, y_train)

# Get the fitted preprocessor from the pipeline
fitted_preprocessor = pipeline.named_steps['preprocessor']

# Transform the training and testing data
X_train_preprocessed = fitted_preprocessor.transform(X_train)
X_test_preprocessed = fitted_preprocessor.transform(X_test)

# Get feature names
feature_names = fitted_preprocessor.vectorizer.get_feature_names_out()

# Convert sparse matrices to dense arrays if needed for further processing or visualization
# Note: For many models, keeping the data in sparse format is more efficient
X_train_dense = X_train_preprocessed.toarray()
X_test_dense = X_test_preprocessed.toarray()

# Create DataFrames (optional, can work with sparse matrices directly with many models)
X_train_preprocessed_df = pd.DataFrame(X_train_dense, columns=feature_names)
X_test_preprocessed_df = pd.DataFrame(X_test_dense, columns=feature_names)

# Display the shapes of the preprocessed data
print("Shape of X_train_preprocessed:", X_train_preprocessed.shape)
print("Shape of X_test_preprocessed:", X_test_preprocessed.shape)

# Display the shapes of the dense arrays (if created)
print("Shape of X_train_dense:", X_train_dense.shape)
print("Shape of X_test_dense:", X_test_dense.shape)

X_train_preprocessed_df.head()

X_test_preprocessed_df.head()

"""## Modeling and Evaluating"""

def evaluate_model_full(model, X_train, y_train, X_test, y_test, model_name, result_df, beta=2, k=5):
    # Convert y_train and y_test to NumPy arrays for consistent indexing
    y_train_np = y_train.values if isinstance(y_train, pd.Series) else y_train
    y_test_np = y_test.values if isinstance(y_test, pd.Series) else y_test

    # ---------- Cross-Validation ----------
    skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
    metrics_cv = {k: [] for k in ['acc', 'prec', 'rec', 'f1', 'fbeta', 'mcc', 'roc_auc']}
    all_y_true_cv = []
    all_y_probs_cv = []

    # Convert to DataFrame for cross-validation
    if hasattr(X_train, 'iloc'):
        X_train_df = X_train
    else:
        X_train_df = pd.DataFrame(X_train)

    for train_idx, val_idx in skf.split(X_train_df, y_train_np): # Use y_train_np here
        X_tr, X_val = X_train_df.iloc[train_idx], X_train_df.iloc[val_idx]
        y_tr, y_val = y_train_np[train_idx], y_train_np[val_idx] # Use y_train_np here

        model.fit(X_tr, y_tr)
        y_pred_val = model.predict(X_val)

        try:
            y_prob_val = model.predict_proba(X_val)[:, 1]
        except:
            y_prob_val = model.decision_function(X_val)
            y_prob_val = (y_prob_val - y_prob_val.min()) / (y_prob_val.max() - y_prob_val.min())


        metrics_cv['acc'].append(balanced_accuracy_score(y_val, y_pred_val))
        metrics_cv['prec'].append(precision_score(y_val, y_pred_val))
        metrics_cv['rec'].append(recall_score(y_val, y_pred_val))
        metrics_cv['f1'].append(f1_score(y_val, y_pred_val))
        metrics_cv['fbeta'].append(fbeta_score(y_val, y_pred_val, beta=beta))
        metrics_cv['mcc'].append(matthews_corrcoef(y_val, y_pred_val))
        metrics_cv['roc_auc'].append(roc_auc_score(y_val, y_prob_val))

        all_y_true_cv.extend(y_val)
        all_y_probs_cv.extend(y_prob_val)

    # ---------- Evaluation on Test Set ----------
    # Use DataFrame for testing
    model.fit(X_train, y_train_np) # Fit on the full training DataFrame, use y_train_np
    y_pred_test = model.predict(X_test)
    try:
        y_prob_test = model.predict_proba(X_test)[:, 1]
    except:
        y_prob_test = model.decision_function(X_test)
        y_prob_test = (y_prob_test - y_prob_test.min()) / (y_prob_test.max() - y_prob_test.min())


    acc_test = balanced_accuracy_score(y_test_np, y_pred_test) # Use y_test_np here
    prec_test = precision_score(y_test_np, y_pred_test) # Use y_test_np here
    rec_test = recall_score(y_test_np, y_pred_test) # Use y_test_np here
    f1_test = f1_score(y_test_np, y_pred_test) # Use y_test_np here
    fbeta_test = fbeta_score(y_test_np, y_pred_test, beta=beta) # Use y_test_np here
    mcc_test = matthews_corrcoef(y_test_np, y_pred_test) # Use y_test_np here
    roc_auc_test = roc_auc_score(y_test_np, y_prob_test) # Use y_test_np here

    # ---------- Plot ROC & PR on Test Set ----------
    fpr, tpr, _ = roc_curve(y_test_np, y_prob_test) # Use y_test_np here
    precision_curve, recall_curve, _ = precision_recall_curve(y_test_np, y_prob_test) # Use y_test_np here

    plt.figure(figsize=(14, 5))

    plt.subplot(1, 2, 1)
    plt.plot(fpr, tpr, label=f'AUC = {roc_auc_test:.2f}')
    plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
    plt.title(f"ROC Curve - {model_name}")
    plt.xlabel("FPR")
    plt.ylabel("TPR")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(recall_curve, precision_curve)
    plt.title(f"Precision-Recall Curve - {model_name}")
    plt.xlabel("Recall")
    plt.ylabel("Precision")

    plt.tight_layout()
    plt.show()

    # ---------- Add to Results ----------
    new_row = pd.DataFrame([{
        'Model': model_name,
        # Train (CV)
        'Train Accuracy': np.mean(metrics_cv['acc']),
        'Train Precision': np.mean(metrics_cv['prec']),
        'Train Recall': np.mean(metrics_cv['rec']),
        'Train F1': np.mean(metrics_cv['f1']),
        'Train Fβ': np.mean(metrics_cv['fbeta']),
        'Train MCC': np.mean(metrics_cv['mcc']),
        'Train ROC AUC': np.mean(metrics_cv['roc_auc']),
        # Test
        'Test Accuracy': acc_test,
        'Test Precision': prec_test,
        'Test Recall': rec_test,
        'Test F1': f1_test,
        'Test Fβ': fbeta_test,
        'Test MCC': mcc_test,
        'Test ROC AUC': roc_auc_test,
    }])

    result_df = pd.concat([result_df, new_row], ignore_index=True)
    return result_df

pipeline_result = pd.DataFrame()

pipeline_result = evaluate_model_full(
    pipeline,
    X_train, y_train,
    X_test, y_test,
    "XGBoost Classifer (Pipeline)",
    pipeline_result
)

pipeline_result

classifiers = {
    # 'Logistic Regression': LogisticRegression(n_jobs=-1, random_state=42),
    # 'Decision Tree': DecisionTreeClassifier(random_state=42),
    # 'Random Forest': RandomForestClassifier(n_jobs=-1, random_state=42),
    # 'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    # 'XGBoost': XGBClassifier(random_state=42),
    # 'SVM': SVC(random_state=42),
    # 'KNN': KNeighborsClassifier(n_neighbors=5, n_jobs=-1),
    # 'Naive Bayes': GaussianNB(),
    # 'AdaBoost': AdaBoostClassifier(random_state=42),
    # 'Bagging': BaggingClassifier(random_state=42),
    # 'CatBoost': CatBoostClassifier(verbose=0, random_state=42),
    # 'LightGBM': LGBMClassifier(random_state=42),
    'Extra Trees': ExtraTreesClassifier(n_jobs=-1, random_state=42),
    # 'MLP': MLPClassifier(random_state=42),
}

results_df = pd.DataFrame()

for model_name, model in classifiers.items():
    results_df = evaluate_model_full(
        model,
        X_train_preprocessed_df, y_train,
        X_test_preprocessed_df, y_test,
        model_name,
        results_df)

results_df.sort_values(by='Test F1', ascending=False)

"""## Fine-tuning the model"""

def evaluate_and_plot(model, X_train, y_train, X_test, y_test, name):
    model.fit(X_train, y_train)
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    y_test_proba = model.predict_proba(X_test)[:, 1]

    results = {
        'Train Accuracy': balanced_accuracy_score(y_train, y_train_pred),
        'Train Precision': precision_score(y_train, y_train_pred),
        'Train Recall': recall_score(y_train, y_train_pred),
        'Train F1': f1_score(y_train, y_train_pred),
        'Train ROC AUC': roc_auc_score(y_train, model.predict_proba(X_train)[:, 1]),
        'Test Accuracy': balanced_accuracy_score(y_test, y_test_pred),
        'Test Precision': precision_score(y_test, y_test_pred),
        'Test Recall': recall_score(y_test, y_test_pred),
        'Test F1': f1_score(y_test, y_test_pred),
        'Test ROC AUC': roc_auc_score(y_test, y_test_proba)
    }

    print(f"📊 Model: {name}")
    print(pd.Series(results))

    # Confusion Matrix
    ConfusionMatrixDisplay.from_predictions(y_test, y_test_pred)
    plt.title(f"Confusion Matrix - {name}")
    plt.show()

    # ROC Curve
    fpr, tpr, _ = roc_curve(y_test, y_test_proba)
    plt.plot(fpr, tpr, label=f"AUC = {results['Test ROC AUC']:.2f}")
    plt.plot([0,1],[0,1], '--', color='gray')
    plt.title(f"ROC Curve - {name}")
    plt.xlabel("FPR")
    plt.ylabel("TPR")
    plt.legend()
    plt.grid()
    plt.show()

    return results

def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 500, step=100),
        'max_depth': trial.suggest_int('max_depth', 5, 50),
        'min_samples_split': trial.suggest_int('min_samples_split', 2, 10),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2']),
        'random_state': 42,
        'n_jobs': -1
    }

    model = ExtraTreesClassifier(**params)

    skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

    scores = cross_val_score(model, X_train_preprocessed_df, y_train, cv=skf, scoring=make_scorer(f1_score))
    return scores.mean()

study = optuna.create_study(direction='maximize', sampler=TPESampler(seed=42))
study.optimize(objective, n_trials=10, show_progress_bar=True)

print("✅ Best parameters found:", study.best_params)
print("🎯 Best F1 Score:", study.best_value)

best_model = ExtraTreesClassifier(**study.best_params)
best_model.fit(X_train_preprocessed_df, y_train)

# Saving the model
joblib.dump(best_model, "best_extratrees_model.pkl")
joblib.dump(pipeline.named_steps['preprocessor'], "preprocessor.pkl")

# Load the model
best_model = joblib.load("best_extratrees_model.pkl")

