# -*- coding: utf-8 -*-
"""Stock_Exchange_Market.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jKvjwofFAwpG9t9BmvtKEDCmwkXZ6Rj7

# Stock Exchange Market

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the dataset"""

dataset = pd.read_csv('Stock_ABAD1.csv')
X = dataset[['<HIGH>', '<LOW>', '<VALUE>', '<VOL>', '<OPEN>', '<LAST>']]
y = dataset['<CLOSE>']

X.head()

y.head()

"""## Spliting the dataset into training set and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=24)

X_train.shape

X_test.shape

y_train.shape

y_test.shape

"""## Feature Scaling"""



"""## Training the model"""

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

"""## Predicting a new data"""

y_new_pred = model.predict([[2000, 1800, 560735268, 220000, 1700, 2000]])
print("Result: {}".format(y_new_pred))

"""## Predicting the model with test set"""

y_pred = model.predict(X_test)
print(y_pred)

"""## Evaluating the model"""

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

print("MSE: {}".format(mean_squared_error(y_test, y_pred)))
print("MAE: {}".format(mean_absolute_error(y_test, y_pred)))
print("R Squared: {}".format(r2_score(y_test, y_pred)))

"""## Visualising"""