# -*- coding: utf-8 -*-
"""Naive_Bayse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bswPKSGE5RJk3PI5RFfZFtJ8i9apRhym

# Naive Bayse

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the dataset"""

from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()
X = dataset.data
y = dataset.target

pd.DataFrame(dataset.data, columns=dataset.feature_names).head(10)

pd.DataFrame(dataset.target).tail(10)

X.shape

y.shape

dataset.feature_names

dataset.target_names

dataset.DESCR

dataset.keys()

"""## Spliting the dataset into training set and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape

X_test.shape

y_train.shape

y_test.shape

"""## Training the model"""

from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

"""## Predicting the test set"""

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix
score = accuracy_score(y_test, y_pred)
matrix = confusion_matrix(y_test, y_pred)

print("Accuracy Score: {:.2f}%\n".format(score * 100))
print("Confusion Matrix:\n{}".format(matrix))