# -*- coding: utf-8 -*-
"""Data_Cleanning_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oglWYKn3TJvAXBgo4DWNI-NzH7BV9Hkb
"""

import pandas as pd

df = pd.read_excel('Customer Call List.xlsx')
df

df = df.drop_duplicates()
df

df = df.drop(columns='Not_Useful_Column')
df

df['Last_Name'] = df['Last_Name'].str.strip('/123._')
df

# df['Phone_Number'] = df['Phone_Number'].str.replace('[^a-zA-Z0-9]','', regex=True)
# df['Phone_Number'] = df['Phone_Number'].apply(lambda x: str(x))
# df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
# df['Phone_Number'] = df['Phone_Number'].str.replace('nan--', '')
# df['Phone_Number'] = df['Phone_Number'].str.replace('Na--', '')
df['Phone_Number']

df[['Street_Address', 'State', 'Zip_Code']] = df['Address'].str.split(',', expand=True)
df

df['Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y')
df['Paying Customer'] = df['Paying Customer'].str.replace('No', 'N')
df['Paying Customer']

df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes', 'Y')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No', 'N')
df['Do_Not_Contact']

df

df = df.replace('N/a', '')
df = df.fillna('')

for x in df.index:
    if df.loc[x, 'Phone_Number'] == '':
        df.drop(x, inplace=True)
df

df = df.reset_index(drop=True)

df

df = df.drop(columns='Address')
df

