# -*- coding: utf-8 -*-
"""Multiple_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FfOiZur7EWDMXuWml0KmHTouP2wOU0a9

# Mulitiple Linear Regression

## Import libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Import dataset"""

dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print("X shape: ",X.shape)
print("y shape: ",y.shape)

pd.DataFrame(X).head()

"""## Encoding categorical data"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

pd.DataFrame(X).head()

"""## Spliting dataset into training and test set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=24)

"""## Training the multiple linear regression"""

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

"""## Predicting the test data"""

y_pred = model.predict(X_test)

"""## Score of model"""

from sklearn.metrics import r2_score
r_squared = r2_score(y_test, y_pred)
print("R Squared: ", np.floor(r_squared * 100))