# -*- coding: utf-8 -*-
"""Feature_Scaling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qnTBk2hwJTyeD7ZUnyC0pl2QgMKQpV1l
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

import warnings
warnings.filterwarnings('ignore')

df = pd.read_excel('Feature_Scaling.xlsx')

df

df.columns

df_sub = df[['Age', 'Team Size', 'Sales']]

df_sub

columns_to_scale = df_sub.columns
plt.figure(figsize=(20, 4))

for i in range(len(df_sub.columns)):
    plt.subplot(1, 3, i+1)
    sns.kdeplot(x = columns_to_scale[i], data = df_sub, fill = 'blue')
    plt.title("Distribution of " + columns_to_scale[i])
    plt.yticks([])

plt.tight_layout()
plt.show()

columns_to_scale = df_sub.columns
plt.figure(figsize=(12, 4))

for i in range(len(df_sub.columns)):
    plt.subplot(1, 3, i+1)
    sns.boxplot(y = columns_to_scale[i], data = df_sub)
    plt.title("Distribution of " + columns_to_scale[i])
    plt.yticks([])

plt.tight_layout()
plt.show()

scaler1 = StandardScaler()
scaler1.fit_transform(df_sub)

scaled_output1 = pd.DataFrame(scaler1.fit_transform(df_sub), columns = df_sub.columns)
scaled_output1

plt.figure(figsize=(12, 4))

for i in range(len(df_sub.columns)):
    plt.subplot(1, 3, i+1)
    sns.kdeplot(x = columns_to_scale[i], data = scaled_output1, fill = 'blue')
    plt.title("Scaled Distribution of " + columns_to_scale[i])
    plt.yticks([])

plt.tight_layout()
plt.show()

scaler2 = MinMaxScaler()
scaled_output2 = pd.DataFrame(scaler2.fit_transform(df_sub), columns = df_sub.columns)
scaled_output2

plt.figure(figsize=(12, 4))

for i in range(len(df_sub.columns)):
  plt.subplot(1, 3, i+1)
  sns.kdeplot(x = columns_to_scale[i], data = scaler_output2, fill = 'blue')
  plt.title("Scaled Distribution of " + columns_to_scale[i])
  plt.yticks([])

plt.tight_layout()
plt.show()

df_sub.mean()

df_sub['Age'].loc[1] = 100
df_sub['Age'].loc[5] = 50

df_sub['Sales'].loc[2] = 30
df_sub['Sales'].loc[7] = 500000
df_sub['Sales'].loc[9] = 300000

df_sub['Team Size'].loc[0] = 50

df_sub.mean()

scaler3 = RobustScaler()
scaled_output3 = pd.DataFrame(scaler3.fit_transform(df_sub), columns = df_sub.columns)
scaled_output3

plt.figure(figsize=(12, 4))

for i in range(len(df_sub.columns)):
  plt.subplot(1, 3, i+1)
  sns.kdeplot(x = columns_to_scale[i], data = scaler_output3, fill = 'blue')
  plt.title("Scaled Distribution of " + columns_to_scale[i])
  plt.yticks([])

plt.tight_layout()
plt.show()

print("Standard Scaler")
print(scaled_output1.max())
print(" ")
print("MinMax Scaler")
print(scaled_output2.max())
print(" ")
print("Robust Scaler")
print(scaled_output3.max())

print("Standard Scaler")
print(scaled_output1.min())
print(" ")
print("MinMax Scaler")
print(scaled_output2.min())
print(" ")
print("Robust Scaler")
print(scaled_output3.min())