# -*- coding: utf-8 -*-
"""Decision_Tree_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aI7fliaJMevJRjkx6zBN0SPeNH-beqUu

# Decision Tree Regression

## Import libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Import dataset"""

dataset = pd.read_csv('Position_Salaries.csv')
df = pd.DataFrame(dataset)
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

df.head()

print(X)

print(y)

"""## Training the model"""

from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(random_state=0)
model.fit(X, y)

"""## Predict the model"""

y_pred = model.predict([[6.5]])
print(y_pred)

"""## Visualising the Decision Tree Regression"""

X_grid = np.arange(min(X), max(X), 0.1)
X_grid = X_grid.reshape(len(X_grid), 1)
plt.scatter(X, y, color='blue')
plt.plot(X_grid, model.predict(X_grid), color='red')
plt.title('Bruth or bluff (Decision Tree Regressor)')
plt.xlabel('Level')
plt.ylabel('Salary')
plt.show()